config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :items
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   def index
     @list = List.find(params[:list_id])
     @items = @list.items
   end

   def new
    @list = List.find(params[:list_id])
    @item = Item.new
   end

  def create
    @list = List.find(params[:list_id])
    @list.items.create(item_params)
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @list.items.find(params[:id]).update(item_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:list_id])
    @list.items.find(params[:id]).destroy
    redirect_to list_path(@list)
  end

  private
   def item_params
     params.require(:item).permit(:title)
   end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @items = List.find(params[:id]).items
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to lists_path
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
   @list = List.find(params[:id])
   @list.update(list_params)
   redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end



 private
   def list_params
     params.require(:list).permit(:title)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/edit.html.erb
<h1>Change <%= @item.title %> in: <%= @list.title %></h1>

<%= form_for [@list, @item] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/items/new.html.erb
<h1>New task for: <%= @list.title %></h1>

<%= form_for [@list, @item] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<h1>Change It Up</h1>

<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'new list name' %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>List of Lists</h1>
<br />
<%= link_to 'Create New List', new_list_path %>

<% if @lists.any? %>
  <ul>
    <% @lists.each do |list| %>
        <li>
          <%= link_to list.title, list_path(list) %>
        </li>
    <% end %>
  </ul>
   <% else %>
      <h2>No lists here, create some</h2>
<% end %>

app/views/lists/new.html.erb
<h1>Name Your List</h1>

<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'new list name' %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>Items for: <%= @list.title %></h1>
<br />

<%= link_to 'Add item', new_list_item_path(@list) %>
<%= link_to 'Change List Name', edit_list_path %>
<%= link_to 'Delete This List', list_path(@list), method: :delete, data: {confirm: 'Delete this list?'}  %>
<br />
<%if @items.any? %>
    <% @list.items.each do |item| %>
        <%= item.title %>
        <%= link_to 'Edit', edit_list_item_path(@list, item) %>
        <%= link_to 'Remove', list_item_path(@list, item), method: :delete, data: {confirm: 'Are you sure?'} %>
        <br />
    <% end %>
  </ul>
<% else %>
  <h2>No items. Make some plans and put them here</h2>
<% end%>
<hr />

<%= link_to 'Back to lists', lists_path %>